============================= test session starts ==============================
platform linux2 -- Python 2.7.6 -- py-1.4.25 -- pytest-2.6.3
plugins: ipynb
collected 0 items / 1 errors

==================================== ERRORS ====================================
____________________ ERROR collecting finmag_nb_test.ipynb _____________________
/usr/local/lib/python2.7/dist-packages/_pytest/runner.py:139: in __init__
    self.result = func()
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:439: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:316: in _memoizedcall
    res = function()
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:439: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
E   TypeError: 'NoneType' object is not iterable
=========================== 1 error in 0.08 seconds ============================
